name: ddonovan
favicon: null
layout_spectrum: 0.9977992416825145
typography_spectrum: 0.7629448990337551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8fffe'
    - '#414f6d'
    - '#8596b9'
    - '#e1d5cd'
  brandStrength: 0.47083717049099505
  lightness: 0.6015269223134965
  saturation: 0.6463746670633554
  rhythmicContrast: 0.1461173400748521
purpose: []
